### ISSUE TITLE
Show visual breakdown on shareable view

### ISSUE THREAD

**Issue by eightfivezero** [Packstack-Tech/app#12]
When sharing a link to a pack list it'd be great to see the visual breakdown on top of the list.

PS. on my search for a lighterpack alternative I stumbled upon packstack and I really like what has been created so far and it's amazing to see that it's actively being worked on! Do you accept PRs from outside contributors?

**Comment by maplethorpej** [comment]
Hey @eightfivezero ! I'm glad you're enjoying it. And yes, I definitely accept code contributions.

Thanks for the reminder on this one, it's been in my backlog and I forgot to create an issue for it.

**Comment by maplethorpej** [comment]
Moved this issue to the public repo: https://github.com/Packstack-Tech/public/issues/4
