### ISSUE TITLE
Deduct only one item's weight from base weight when marked as worn

### ISSUE THREAD

**Issue by eightfivezero** [Packstack-Tech/app#14]
For instance, I bring the same shirt twice on a hike so I set the quantity to 2. When I mark that item as worn it should probably only deduct one shirt's weight from the base weight. 
Right now I can't think of a case where I'd need to deduct all items from the base weight if I mark it as worn. ✌️

**Comment by maplethorpej** [comment]
Yeah, I think it makes sense to only deduct one item from the base weight. That seems intuitive to me. Thanks for checking how LighterPack handles this.
