### ISSUE TITLE
Quantity and 'worn' state of items in packing list should update correctly after drag and drop

### ISSUE THREAD

**Issue by eightfivezero** [Packstack-Tech/app#17]
When reordering items in the packlist the items drop at the right spot but the quantity and 'worn' state don't update. 

See screencap:

https://github.com/Packstack-Tech/app/assets/1029855/73609fa7-4add-420a-8bc1-d67faa20b9f9

Browser refresh shows the quantity and status in the right place again so it's hopefully just a minor scoping issue. 🙏

**Comment by maplethorpej** [comment]
I've spotted the problem with the item quantity, but I'm not able to reproduce the `worn` state issue.
