### ISSUE TITLE
Let users create new items with similar names

### ISSUE THREAD

**Issue by eightfivezero** [Packstack-Tech/app#18]
I keep running into the issue that I can't create an item with a product name how I want to name it.

For example, I want to create an item as follows:
Manufacturer: Leatherman
Product name: Micra

But someone else created a product like this:
Manufacturer: Leatherman
Product name: Leatherman Micra

The system always autocompletes to "Leatherman Leatherman Micra" now and there's nothing I can do about it. 😅 

Same with Manufacturers. I want to create an item with the manufacturer "Loop" but I can only create an item with "E-Loop" or "Loopalien" as Manufacturer.

It'd be great if, regardless of what already exists in the database, there's always an option to create a new manufacturer or product name at the end of the autocomplete dropdown. 🙏

**Comment by micleb** [comment]
Hello,

Yes I agree, I have the same issue.
For example the brand "armytek" already exists but I wanted to name it "Armytek" (with an uppercase letter) in my list and it's not possible.

**Comment by maplethorpej** [comment]
This is a slightly harder problem than it first appears since I don't want duplicate names in the system, but I agree that you should be able to name things how you want to. I'll see what I can do about this 🙌

**Comment by iikku** [comment]
It's not just about naming things the way we wanto to, it's also about adding products to the database. There currently exists manufacturer NEMO with product Dagger Osmo 2P - which means I cannot add the older product Dagger 2P.

**Comment by maplethorpej** [comment]
AH, you're totally right. Let me see if I can get a quick fix in for this.

**Comment by maplethorpej** [comment]
Fix released. Let me know if you still encounter issues with this, and thanks for reporting!
