### ISSUE TITLE
Improve csv file imports

### ISSUE THREAD

**Issue by micleb** [Packstack-Tech/app#24]
Hello,

When we export our inventory from PackStack we get a CSV file with the following columns :
`name | manufacturer | category | product | weight | unit | price | consumable | product_url | notes`

But it is only possible to import CSV from lighterpack with those columns : 
`Item Name | Category | desc | qty | weight | unit | url | price | worn | consumable`

Thus, multiple fields are not completed, especially the product and the manufacturer.

Please, add the possibility to import CSV files with the following columns : 
`name | manufacturer | category | product | weight | unit | price | consumable | product_url | notes`

Thank you

**Comment by maplethorpej** [comment]
Agreed! I'll be working on this is in January.
