### ISSUE TITLE
Theme: Light mode

### ISSUE THREAD

**Issue by maplethorpej** [Packstack-Tech/app#3]
Some users have requested a light UI mode. This can be added to the tailwind configuration, and should appear as an option on the Settings page. Setting should be saved to local storage.

**Comment by bilalshaikh292** [comment]
heyy @maplethorpej   is the issue still open ? I would like to contribute ?

**Comment by maplethorpej** [comment]
Hey @bilalshaikh292 ! Yes, this is still open. Would love to have you contribute.

**Comment by NoahMLoomis** [comment]
I've got a version with a toggle in the settings page that works, but it looks like any tailwind styles would need to be modified for light mode as well. The way I've done light/dark mode in the past is with the tailwind prefix `dark:some-style-here`, but it doesn't seem that exists in this project.

Is there maybe an easier way to add light mode that doesn't include manually changing all the styles to add `dark` properties?

**Comment by maplethorpej** [comment]
@NoahMLoomis I haven't experimented with creating a light mode yet, but we may have to do whatever tailwind suggests is the standard approach. Could be a pain

**Comment by NoahMLoomis** [comment]
Thanks for the input, good to know. I'll look into doing it with Copilot, i think it would make things go a lot faster. 

You're probably right about following the standard of using `dark` classes everywhere is the simplest approach

**Comment by maplethorpej** [comment]
Agreed @eightfivezero @NoahMLoomis – it'll probably be more verbose to add `dark:` classes but I think the added control is worth it.

**Comment by Hund** [comment]
I'm looking forward to this! Dark websites are a pure nightmare for your eyes health.
