### ISSUE TITLE
Renamed lists show the old name in the list view

### ISSUE THREAD

**Issue by Reedyn** [Packstack-Tech/app#38]
When duplicating a list it gets the name `untitled` however when this is changed to something else it still retains the original `untitled`-name in the list view. When viewing the actual list it displays the new name.

**Comment by maplethorpej** [comment]
@Reedyn I wasn't able to reproduce but I think this was an issue with older packs. Can you confirm that the label in the list is correct now?

**Comment by Reedyn** [comment]
> @Reedyn I wasn't able to reproduce but I think this was an issue with older packs. Can you confirm that the label in the list is correct now?

I still see the issue. I tried duplicating another list and that one also "locks" to the first given name even when I change the name.

![image](https://github.com/Packstack-Tech/app/assets/947063/1c2fd6f1-7a43-4cee-977a-7d231ac07ea6)

**Comment by Reedyn** [comment]
I just saw that this is still an issue, I now have a long list of "untitled".

![image](https://github.com/Packstack-Tech/app/assets/947063/f13a9b32-588c-4e20-a77f-28013d46c467)
